version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c 'yarn dev'
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
